# fly.toml app configuration file generated for planetary-hours on 2025-09-09T22:57:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'planetary-hours'
primary_region = 'mia'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
