# fly.toml app configuration file generated for planetary-hours on 2025-09-09T22:57:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'planetary-hours'
primary_region = 'mia'
console_command = '/rails/bin/rails console'

[build]

[env]
  PORT = "3000"
  RAILS_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
